// Import necessary components
import Card from '../components/Card';
import { useEffect, useRef, useState } from 'react';
import useIntersectionObserver from '../hooks/useIntersectionObserver'; // We'll create this hook later





function GlobalWarmingPage() {

  // Introduction Section Ref and Animation State
  const introRef = useRef(null);
  const introVisible = useIntersectionObserver(introRef, 0.1);

  const causesData = [
    {
      title: 'Generating Power',
      description:
        'Generating electricity and heat by burning fossil fuels causes a large chunk of global emissions. Most electricity is still generated by burning coal, oil, or gas, which produces carbon dioxide and nitrous oxide – powerful greenhouse gases that blanket the Earth and trap the sun’s heat. Globally, a bit more than a quarter of electricity comes from wind, solar and other renewable sources which, as opposed to fossil fuels, emit little to no greenhouse gases or pollutants into the air.',
      imageSrc: '/images/gl-1.png',
    },
    {
      title: 'Manufacturing Goods',
      description:
        'Manufacturing and industry produce emissions, mostly from burning fossil fuels to produce energy for making things like cement, iron, steel, electronics, plastics, clothes, and other goods. Mining and other industrial processes also release gases, as does the construction industry. Machines used in the manufacturing process often run on coal, oil, or gas; and some materials, like plastics, are made from chemicals sourced from fossil fuels. The manufacturing industry is one of the largest contributors to greenhouse gas emissions worldwide.',
      imageSrc: '/images/gl-2.jpg',
    },
    {
      title: 'Cutting Down Forests',
      description:
        'Cutting down forests to create farms or pastures, or for other reasons, causes emissions, since trees, when they are cut, release the carbon they have been storing. Each year approximately 12 million hectares of forest are destroyed. Since forests absorb carbon dioxide, destroying them also limits nature’s ability to keep emissions out of the atmosphere. Deforestation, together with agriculture and other land use changes, is responsible for roughly a quarter of global greenhouse gas emissions.',
      imageSrc: '/images/gl-3.avif',
    },
    {
      title: 'Using Transportation',
      description:
        'Most cars, trucks, ships, and planes run on fossil fuels. That makes transportation a major contributor of greenhouse gases, especially carbon-dioxide emissions. Road vehicles account for the largest part, due to the combustion of petroleum-based products, like gasoline, in internal combustion engines. But emissions from ships and planes continue to grow. Transport accounts for nearly one quarter of global energy-related carbon-dioxide emissions. And trends point to a significant increase in energy use for transport over the coming years.',
      imageSrc: '/images/gl-4.jpeg',
    },
    {
      title: 'Producing Food',
      description:
        'Producing food causes emissions of carbon dioxide, methane, and other greenhouse gases in various ways, including through deforestation and clearing of land for agriculture and grazing, digestion by cows and sheep, the production and use of fertilizers and manure for growing crops, and the use of energy to run farm equipment or fishing boats, usually with fossil fuels. All this makes food production a major contributor to climate change. And greenhouse gas emissions also come from packaging and distributing food.',
      imageSrc: '/images/gl-5.jpg',
    },
    {
      title: 'Powering Buildings',
      description:
        'Globally, residential and commercial buildings consume over half of all electricity. As they continue to draw on coal, oil, and natural gas for heating and cooling, they emit significant quantities of greenhouse gas emissions. Growing energy demand for heating and cooling, with rising air-conditioner ownership, as well as increased electricity consumption for lighting, appliances, and connected devices, has contributed to a rise in energy-related carbon-dioxide emissions from buildings in recent years.',
      imageSrc: '/images/gl-6.jpg',
    },
    {
      title: 'Consuming Too Much',
      description:
        'Your home and use of power, how you move around, what you eat and how much you throw away all contribute to greenhouse gas emissions. So does the consumption of goods such as clothing, electronics, and plastics. A large chunk of global greenhouse gas emissions are linked to private households. Our lifestyles have a profound impact on our planet. The wealthiest bear the greatest responsibility: the richest 1 per cent of the global population combined account for more greenhouse gas emissions than the poorest 50 per cent.',
      imageSrc: '/images/gl-7.jpg',
    }
  ]

  const effectsData = [
    {
      title: 'Longer Wildfire Season',
      description:
        'Warming temperatures have extended and intensified wildfire season in the West, where long-term drought in the region has heightened the risk of fires. Scientists estimate that human-caused climate change has already doubled the area of forest burned in recent decades. By around 2050, the amount of land consumed by wildfires in Western states is projected to further increase by two to six times. Even in traditionally rainy regions like the Southeast, wildfires are projected to increase by about 30%.',
      imageSrc: '/images/gl-8.jpg',
    },
    {
      title: 'More Droughts and Heat Waves',
      description:
        'In 2024, the world faced some of the worst drought conditions globally, particularly in the Amazon River Basin where drought was made 30 times more likely due to climate change, threatening tree health and carbon storage. In Mexico, the worst drought since 2011 led to severe water scarcity and agricultural challenges, exacerbating heat waves that resulted in over 125 heat-related deaths since March 2024 and thousands suffering from heat-related illnesses due to prolonged high temperatures. The summer of 2024 was marked by unprecedented heat, with average global temperatures surpassing 1.5°C above pre-industrial levels for the first time, leading to an average exposure of an additional 41 days of extreme heat. Studies suggest that if global temperatures rise by 2°C above pre-industrial levels, prolonged hot and dry conditions could increase significantly, with periods of extreme weather lasting longer than two weeks becoming 10% more likely in central North America. ',
      imageSrc: '/images/gl-9.jpg',
    },
    {
      title: 'Arctic Is Very Likely to Become Ice-Free',
      description:
        'Scientists predict that the Arctic could become ice-free much sooner than previously anticipated, potentially experiencing its first ice-free summer as early as 2030 and likely between 2030 and 2050. Arctic sea ice is melting at an unprecedented rate of over 12% per decade, with summer sea ice decreasing by approximately 73,000 km² annually since 1979. An ice-free Arctic is expected to be a rare event at 1.5°C of global warming, frequent at 2°C, and could become permanent above 2.5°C. Drastic reductions in carbon dioxide emissions could delay the first ice-free summer and mitigate impacts on the global climate system.',
      imageSrc: '/images/gl-10.webp',
    },
    {
      title: 'Changes in Precipitation Patterns',
      description:
        'Since 1901, global precipitation has increased at an average rate of 0.03 inches per decade, with the contiguous United States experiencing a higher increase of 0.18 inches per decade. High latitude regions are likely to see increased precipitation, while subtropical areas are projected to have decreased precipitation due to rising temperatures. Since 2015, daily rainfall has deviated from natural variability more than 50% of the time because of human-induced global warming. Rising temperatures intensify the Earth\'s water cycle, leading to more frequent and intense storms, increased flooding risks in storm-affected areas, and higher drought risks in regions away from storm tracks. Climate models predict that these complex precipitation changes will continue, varying by region based on local water availability and climate conditions.',
      imageSrc: '/images/gl-11.jpg',
    },
    {
      title: 'Global Temperatures Will Continue to Rise',
      description:
        'In November 2024, Earth\'s global average surface temperature was 1.57°C above the pre-industrial baseline of 1880-1920, marking it as the second warmest November since records began in 1880. Over the past decade, November temperatures have averaged 1.21°C above this baseline, highlighting a persistent warming trend. This significant rise in global temperatures intensifies impacts on humans and nature, including more frequent and severe extreme weather events, threats to food and water security, health risks from heatwaves, and loss of biodiversity. If this trend continues, future generations may face escalating challenges such as sea-level rise, disrupted ecosystems, and increased frequency of natural disasters, emphasizing the urgent need for comprehensive climate action now. Addressing these issues is crucial to mitigate future risks and protect the well-being of both humanity and the natural world.',
      imageSrc: '/images/gl-12.jpg',
    },
    {
      title: 'U.S. Sea Level Likely to Rise 1 to 6.6 Feet by 2100',
      description:
        'Global sea level has risen about 8 inches (0.2 meters) since reliable record-keeping began in 1880. By 2100, scientists project that it will rise at least another foot (0.3 meters), but possibly as high as 6.6 feet (2 meters) in a high-emissions scenario. Sea level is rising because of added water from melting land ice and the expansion of seawater as it warms.',
      imageSrc: '/images/gl-13.jpg',
    },
    {
      title: 'Loss of Species',
      description:
        'Around one million animal and plant species are now threatened with extinction, according to the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES). Climate change is a significant factor, affecting at least 10,967 species on the IUCN Red List. Projections indicate that if global temperatures rise by 2°C by 2100, about 18% of all land-based species could face a high risk of extinction. More sensitive species, such as over 30% of insect pollinators and salamanders, are at even greater risk under this scenario. Preserving other species is crucial because biodiversity supports ecosystem functions that are vital for human survival, including pollination, clean water, and air. Our consumption habits contribute to climate change and habitat loss, accelerating species extinction; therefore, adopting sustainable practices is essential to protect these species and maintain the health of our planet.',
      imageSrc: '/images/gl-14.jpg',
    }
  ]


    return (
      <div className="container mx-auto py-8">
      <div
        ref={introRef}
        className={`transition-transform duration-700 ${
          introVisible ? 'transform scale-100 opacity-100' : 'transform scale-95 opacity-0'
        }`}
      >
          <h2 className="text-3xl font-bold mb-6">The Global Warming Crisis</h2>
        <blockquote className="text-lg italic border-l-4 border-green-500 pl-4 mb-6">
          "Global warming is the phenomenon of a gradual increase in the temperature near the earth’s surface. This phenomenon has been observed over the past one or two centuries. This change has disturbed the climatic pattern of the earth. However, the concept of global warming is quite controversial but the scientists have provided relevant data in support of the fact that the temperature of the earth is rising constantly.

          There are several causes of global warming, which have a negative effect on humans, plants, and animals. These causes may be natural or might be the outcome of human activities. In order to curb the issues, it is very important to understand the negative impacts of global warming."
        </blockquote>

      </div>

 <h3 className="text-2xl font-semibold mb-6 mt-10">Causes</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
        {causesData.map((item, index) => (
          <Card
            key={index}
            imageSrc={item.imageSrc}
            title={item.title}
            description={item.description}
          />
        ))}
      </div>

      <h3 className="text-2xl font-semibold mb-6 mt-10">Effects</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
        {effectsData.map((item, index) => (
          <Card
            key={index}
            imageSrc={item.imageSrc}
            title={item.title}
            description={item.description}
          />
        ))}
      </div>
      </div>
    );
  }
  
  export default GlobalWarmingPage;